export { default as About } from './about'
export { default as Certificates } from './certificates'
export { default as Projects } from './projects'
export { default as Project } from './projects/project'
export { default as Work } from './work'
